Data Manipulation and Analysis with Pandas

Data manipulation and analysis are the tasks any data science or data analysis project.

In [1]:
import pandas as pd

In [5]:
reviews = pd.read_csv('wine_data.csv', index_col=0)
reviews.head()

reviews.isnull().sum()

country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [6]:
# fill in missing values with the mean of the column
reviews['price'] = reviews['price'].fillna(reviews['price'].mean())

In [7]:
reviews.dtypes

country                      str
description                  str
designation                  str
points                     int64
price                    float64
province                     str
region_1                     str
region_2                     str
taster_name                  str
taster_twitter_handle        str
title                        str
variety                      str
winery                       str
dtype: object

In [10]:
# renaming the columns

reviews.rename(columns={'points': 'score', 'price': 'cost'}, inplace=True)
reviews.head()

reviews.tail()

,country,description,designation,score,cost,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [11]:
# change data type of a column
reviews['score_Points'] = reviews.score.astype(float)

reviews.head()

,country,description,designation,score,cost,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,score_Points
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,87.0
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,87.0
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.000000,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,87.0
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.000000,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,87.0
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.000000,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,87.0

In [14]:
# apply function

reviews['New Value'] = reviews.score.apply(lambda x: x*2)

reviews.head()

,country,description,designation,score,cost,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,score_Points,New Value
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,87.0,174
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,87.0,174
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.000000,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,87.0,174
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.000000,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,87.0,174
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.000000,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,87.0,174

In [ ]:
# Data aggregating and grouping

grouped_mean = reviews.groupby('country')['score'].mean()

print(grouped_mean)

In [17]:
grouped_sum = reviews.groupby(['country','region_1'])['score_Points'].mean()

print(grouped_sum)

country    region_1
Argentina  Agrelo                      88.480000
           Alto Valle del Río Negro    86.458333
           Altos de Mendoza            86.000000
           Argentina                   85.361111
           Buenos Aires                88.000000
                                         ...
US         Yamhill County              91.000000
           Yolo County                 87.638298
           York Mountain               86.888889
           Yorkville Highlands         88.886076
           Yountville                  89.206522
Name: score_Points, Length: 1230, dtype: float64

In [19]:
# aggregate multiple function

mul_agreegator = reviews.groupby('province')['cost'].agg(['mean', 'sum', 'count', 'max'])

print(mul_agreegator)

                                mean          sum  count    max
province
Achaia                     23.000000   115.000000      5   37.0
Aconcagua Costa            23.074074   623.000000     27   95.0
Aconcagua Valley           40.213162  4664.726778    116  235.0
Aegean                     33.409091   735.000000     22  120.0
Agioritikos                24.000000    72.000000      3   25.0
...                              ...          ...    ...    ...
Zenata                     16.842105   320.000000     19   18.0
Österreichischer Perlwein  16.750000    67.000000      4   21.0
Österreichischer Sekt      28.542681  1883.816946     66   55.0
Štajerska                  17.181818   378.000000     22   31.0
Župa                       27.750000   222.000000      8   42.0

[425 rows x 4 columns]

In [ ]:
# Merging and joining the dataframe
df1 = pd.DataFrame({'Key': ['A','B','C'], 'Value': [1,2,3]})
df12 = pd.DataFrame({'Key': ['A','B','C'], 'Value': [4,5,6]})

df1

  Key  Value
0   A      1
1   B      2
2   C      3