In [3]:
# import numpy and pandas
import numpy as np
import pandas as pd

In [4]:
data = {
    'Name': ['Rakesh', 'Umesh', 'Kohli'],
    'Age': [25,48,37],
    'City': ['Banglore', 'Chikkamagalore', 'Dehli']
}

In [6]:
df = pd.DataFrame(data)

df.head()

     Name  Age            City
0  Rakesh   25        Banglore
1   Umesh   48  Chikkamagalore
2   Kohli   37           Dehli

In [ ]:
data = [['Rakesh', 25, 'Bang'],['Umesh', 49, 'CKM'],['Kohli', 38, 'Dehli']]

df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])

df.head()

     Name  Age   City
0  Rakesh   25   Bang
1   Umesh   49    CKM
2   Kohli   38  Dehli

In [ ]:
# read from html

url = "https://en.wikipedia.org/wiki/Indian_Institutes_of_Information_Technology"

table = pd.read_html(url)
table[0]