Reading data from Different sources

In [ ]:
import pandas as pd


df  =  pd.read_csv('wine_data.csv')

df.to_csv('wine_data_copy.csv', index=False)

In [5]:
# read data from HTML page

url = "https://www.fdic.gov/bank-failures/failed-bank-list"

df = pd.read_html(url)

df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Nano Banc,Irvine,California,58590,Sunwest Bank,"September 25, 2026",10555
1,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
2,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
3,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
4,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
5,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
6,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
7,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
8,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
9,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
10,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
11,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
12,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
13,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
14,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
15,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
16,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
17,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
18,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
19,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
20,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
21,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
22,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
23,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
24,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529

In [6]:
data = df[0]

data.describe()

               Cert  Fund  Sort ascending
count     25.000000             25.000000
mean   29299.920000          10542.040000
std    18171.009958              8.258733
min     4134.000000          10529.000000
25%    16748.000000          10535.000000
50%    25796.000000          10543.000000
75%    33802.000000          10549.000000
max    59017.000000          10555.000000

In [ ]:
# Reading from excel sheet

df = pd.read_excel('youu_data.xlsx')